baseURL = 'https://Saksham03.github.io/'
languageCode = 'en-us'
title = 'The Capable Snakekeeper and all his wrongdoings'
theme = 'dream'
contentDir = "content"

[params]
avatar = "/img/misc/website_logo.jpg"
headerTitle = 'Saksham Nagpal'
motto = "The Capable Snakekeeper"

[[module.mounts]]
source = 'static'
target = 'assets'
